spring:
  cache:
    # GENERIC, JCACHE, HAZELCAST, COUCHBASE, INFINISPAN, REDIS, CACHE2K, CAFFEINE, SIMPLE, NONE;
    type: CAFFEINE
    cache-names: cache1, cache2
  data:
    redis:
      host: dev-middleware-redis
      port: 6379
      password: 123456
      database: 1