#cache:
#  type: ehcache1
spring:
  cache:
    type: jcache
    jcache:
      provider: org.ehcache.jsr107.EhcacheCachingProvider
  data:
    redis:
      host: dev-middleware-redis
      port: 6379
      password: 123456
      database: 1