#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: test_route
#          uri: http://httpbin.org
#          predicates:
#            - Path=/httpbin/**
#          filters:
#            - RewritePath=/httpbin/(?<segment>.*), /$\{segment}