spring:
  cloud:
    gateway:
      routes:
        - id: cookie_route
          uri: https://www.sina.com.cn/
          predicates:
            - Cookie=mycookie,mycookievalue
        - id: after_route
          uri: https://www.sina.com.cn/
          predicates:
            - After=2050-04-20T15:00:00+08:00
        - id: before_route
          uri: https://www.sina.com.cn/
          predicates:
            - Before=2020-04-20T15:00:00+08:00
        - id: between_route
          uri: https://www.sina.com.cn/
          predicates:
            - Between=2040-01-20T17:42:47+08:00, 2050-01-21T17:42:47+08:00
        - id: header_route
          uri: https://www.sina.com.cn/
          predicates:
            - Header=X-Request-Id, \d+
        - id: host_route
          uri: https://www.sina.com.cn/
          predicates:
            - Host=**.dev.com
        - id: method_route
          uri: https://www.sina.com.cn/
          predicates:
            - Method=HEAD,DELETE
        - id: path_route
          uri: https://www.sina.com.cn/
          predicates:
            - Path=/red/{segment},/blue/{segment}
        - id: query_route
          uri: https://www.sina.com.cn/
          predicates:
            - Query=red, gree.
        - id: remoteaddr_route
          uri: https://www.sina.com.cn/
          predicates:
            - RemoteAddr=127.0.0.2/32
        - id: xforwarded_remoteaddr_route
          uri: https://www.sina.com.cn/
          predicates:
            - XForwardedRemoteAddr=192.168.1.1/24
        - id: circuitbreaker_route
          uri: lb://backing-service:8088
          predicates:
            - Path=/consumingServiceEndpoint
          filters:
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                fallbackUri: forward:/error/503
                statusCodes:
                  - 500
                  - "NOT_FOUND"