foo: bar
spring:
  datasource:
    username: root
    password: Ngtrade!@#
    url: jdbc:mysql://127.0.0.1:3306/spring?characterEncoding=utf8&useSSL=false
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
server:
  port: 8080
management:
  #  security:
  #    enabled: false
  server:
    port: 8001
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    mappings:
      enabled: true
